### ISSUE TITLE
Finalize must haves for the first phase of the project.

### ISSUE THREAD

**Issue by shriramsharma** [VoluteeRide/VolunteeRideApp-svc#2]
List down the must haves for the first phase of the project.

**Comment by ayazlakdawala** [comment]
The phase 1 requirements are streamlined and can be tracked from the Requirements Document available at VolunteeRideApp-svc/Documents/RequirementDocuments/VolunteerRideRequirements.docx

Kindly review and let me know if in case there are any changes needed.

**Comment by shriramsharma** [comment]
This issue has been moved to VoluteeRide/VolunteeRideApp-Docs/issues/1
